/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppAlertsRouteImport } from './routes/app/alerts'
import { Route as AppConnectionsRouteImport } from './routes/app/connections'
import { Route as AppCostsRouteImport } from './routes/app/costs'
import { Route as AppProductsRouteImport } from './routes/app/products'
import { Route as AppSettingsRouteImport } from './routes/app/settings'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppConnectProviderRouteImport } from './routes/app/connect.$provider'
import { Route as PWorkspaceProductRouteImport } from './routes/p.$workspace.$product'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAlertsRoute = AppAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AppRoute,
} as any)
const AppConnectionsRoute = AppConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => AppRoute,
} as any)
const AppCostsRoute = AppCostsRouteImport.update({
  id: '/costs',
  path: '/costs',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsRoute = AppProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppConnectProviderRoute = AppConnectProviderRouteImport.update({
  id: '/connect/$provider',
  path: '/connect/$provider',
  getParentRoute: () => AppRoute,
} as any)
const PWorkspaceProductRoute = PWorkspaceProductRouteImport.update({
  id: '/p/$workspace/$product',
  path: '/p/$workspace/$product',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/app/alerts': typeof AppAlertsRoute
  '/app/connections': typeof AppConnectionsRoute
  '/app/costs': typeof AppCostsRoute
  '/app/products': typeof AppProductsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/connect/$provider': typeof AppConnectProviderRoute
  '/p/$workspace/$product': typeof PWorkspaceProductRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/app/alerts': typeof AppAlertsRoute
  '/app/connections': typeof AppConnectionsRoute
  '/app/costs': typeof AppCostsRoute
  '/app/products': typeof AppProductsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/connect/$provider': typeof AppConnectProviderRoute
  '/p/$workspace/$product': typeof PWorkspaceProductRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/app/alerts': typeof AppAlertsRoute
  '/app/connections': typeof AppConnectionsRoute
  '/app/costs': typeof AppCostsRoute
  '/app/products': typeof AppProductsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/connect/$provider': typeof AppConnectProviderRoute
  '/p/$workspace/$product': typeof PWorkspaceProductRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/onboarding'
    | '/app/alerts'
    | '/app/connections'
    | '/app/costs'
    | '/app/products'
    | '/app/settings'
    | '/app/'
    | '/api/auth/$'
    | '/app/connect/$provider'
    | '/p/$workspace/$product'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/app/alerts'
    | '/app/connections'
    | '/app/costs'
    | '/app/products'
    | '/app/settings'
    | '/app'
    | '/api/auth/$'
    | '/app/connect/$provider'
    | '/p/$workspace/$product'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/onboarding'
    | '/app/alerts'
    | '/app/connections'
    | '/app/costs'
    | '/app/products'
    | '/app/settings'
    | '/app/'
    | '/api/auth/$'
    | '/app/connect/$provider'
    | '/p/$workspace/$product'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  PWorkspaceProductRoute: typeof PWorkspaceProductRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/alerts': {
      id: '/app/alerts'
      path: '/alerts'
      fullPath: '/app/alerts'
      preLoaderRoute: typeof AppAlertsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/connections': {
      id: '/app/connections'
      path: '/connections'
      fullPath: '/app/connections'
      preLoaderRoute: typeof AppConnectionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/costs': {
      id: '/app/costs'
      path: '/costs'
      fullPath: '/app/costs'
      preLoaderRoute: typeof AppCostsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/products': {
      id: '/app/products'
      path: '/products'
      fullPath: '/app/products'
      preLoaderRoute: typeof AppProductsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/connect/$provider': {
      id: '/app/connect/$provider'
      path: '/connect/$provider'
      fullPath: '/app/connect/$provider'
      preLoaderRoute: typeof AppConnectProviderRouteImport
      parentRoute: typeof AppRoute
    }
    '/p/$workspace/$product': {
      id: '/p/$workspace/$product'
      path: '/p/$workspace/$product'
      fullPath: '/p/$workspace/$product'
      preLoaderRoute: typeof PWorkspaceProductRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAlertsRoute: typeof AppAlertsRoute
  AppConnectionsRoute: typeof AppConnectionsRoute
  AppCostsRoute: typeof AppCostsRoute
  AppProductsRoute: typeof AppProductsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppConnectProviderRoute: typeof AppConnectProviderRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAlertsRoute: AppAlertsRoute,
  AppConnectionsRoute: AppConnectionsRoute,
  AppCostsRoute: AppCostsRoute,
  AppProductsRoute: AppProductsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
  AppConnectProviderRoute: AppConnectProviderRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  PWorkspaceProductRoute: PWorkspaceProductRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
